name: CNIP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20  * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: make ip list
      run: |
         wget -O CN.txt https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
         { 
           echo "/ip firewall address-list"
           for net in $(cat CN.txt) ; do
             echo "add list=CNIP address=$net comment=CNIP"
           done
         } > ../cnip.rsc
         rm CN.txt
        
    - name: Check for changes
      run: |
        if [[ -n $(git status -s) ]]; then
            git config --global user.email "your_email@example.com"
            git config --global user.name  "xindo451"
            git add -f ./cnip.rsc
            git commit -m "Update cnip"
        fi
        
    - name: Push changes
      run: git push origin master
