name: CNIP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20  * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: make ip list
      run: |
        chmod +x make_list.sh
        ./make_list.sh
        
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
